"""Added count for OrderItem

Revision ID: 9fbc98436a9f
Revises: b82f791ca21a
Create Date: 2024-09-24 22:19:51.220824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbc98436a9f'
down_revision: Union[str, None] = 'b82f791ca21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'order', ['order_id'])
    op.add_column('order_item', sa.Column('product_count', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'order_item', ['order_item_id'])
    op.create_unique_constraint(None, 'product', ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'order_item', type_='unique')
    op.drop_column('order_item', 'product_count')
    op.drop_constraint(None, 'order', type_='unique')
    # ### end Alembic commands ###
